displayName=Wintertodt Notifications
author=Jodelahithit
support=https://github.com/erwinvc/runelite-plugins
description=Visual notifications for Wintertodt
tags=notification,wintertodt,visual,idle
version=
plugins=eu.jodelahithit.WintertodtNotificationsPlugin
build=standard