displayName=Skilling Notifications
author=Jodelahithit
support=https://github.com/erwinvc/runelite-plugins
description=Visual notifications on idling from skilling
tags=notifications,skilling,idle,idling
version=
plugins=eu.jodelahithit.SkillingNotificationsPlugin
build=standard